import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from "next/link";
import Script from "next/script";
import BasicModal from '../component/Modal/BasicModal';
import { Menu, Icon } from 'semantic-ui-react';
import { useEffect, useState } from "react";
import useAuth from '../hooks/useAuth';
import { getMeApi } from "../pages/api/user";
// add bootstrap css 
//import 'bootstrap/dist/css/bootstrap.css';

import 'semantic-ui-css/semantic.min.css';

import NavBar from '../component/NavBar';
import Auth from '../component/Auth/Auth';

export default function Home() {


  const [showModal, setShowModal] = useState(false);

  const onShowModal = () => setShowModal(true);
  const onCloseModal = () => setShowModal(false);

  const [user, setUSer] = useState(undefined);

  const { auth, logout } = useAuth();


  useEffect(() => {
    (async () => {
      const response = await getMeApi(logout);
      setUSer(response)

    })();
  }, [auth]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar></NavBar>
      <main className={styles.main}>
        <h1>Hola XD</h1>
        {user !== undefined &&
          <MenuOptions onShowModal={onShowModal} user={user} logout={logout}></MenuOptions>}


        <BasicModal show={showModal} title="Crea tu cuenta" setShow={setShowModal} size="small">
          <Auth onCloseModal={onCloseModal}></Auth>
        </BasicModal>
        <Link href="/contacto">
          Contacto
        </Link>
      </main>
      <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossOrigin="anonymous"
      />
    </div>
  )

  function MenuOptions(props) {
    const { onShowModal, user, logout } = props;
    return (
      <Menu>
        {user ? (
          <>
            <Link href="/orders">
              <Menu.Item>
                <Icon name='money'></Icon>
                mis ganancias
              </Menu.Item>
            </Link>
            <Link href="/orders">
              <Menu.Item>
                <Icon name='money'></Icon>
                mis perdidas
              </Menu.Item>
            </Link>
            <Link href="/cuenta">
              <Menu.Item>
                <Icon name='user outline'></Icon>
                {user.username}
              </Menu.Item>
            </Link>


            <Menu.Item onClick={logout}>
              <Icon name='power off'></Icon>
            </Menu.Item>
          </>
        ) : (
          <Menu.Item onClick={onShowModal}>
            <Icon name="user outline"></Icon>
          </Menu.Item>
        )}

      </Menu>
    );
  }
}
